import { Fragment } from "react";
import { Icon } from "../../../components/icon";
import { PageHeader } from "../../../components/page-header";
import { TeamSubnav } from "../../../components/team-subnav";
import { Button } from "../../../components/ui";
import { adminRoles, permissionCatalog } from "../../../data/mock-admin";

export default function TeamRolesPage() {
  return <div className="page-stack governance-page"><PageHeader eyebrow="Equipe / Perfis e permissões" title="Perfis e permissões" description="RBAC previsível: cada perfil recebe somente o necessário para executar seu trabalho." actions={<Button icon="plus" disabled title="Criação de perfis será habilitada com persistência e API">Novo perfil</Button>}/><TeamSubnav/><section className="role-card-grid">{adminRoles.map((role) => <article className={`role-card role-${role.tone}`} key={role.id}><header><span className="role-card-icon"><Icon name={role.id === "admin" ? "shield" : role.id === "operations" ? "boxes" : role.id === "commercial" ? "handshake" : role.id === "marketing" ? "megaphone" : role.id === "finance" ? "wallet" : "users"} size={16}/></span><span className="role-system">{role.system ? "Sistema" : "Personalizado"}</span></header><h2>{role.name}</h2><p>{role.description}</p><footer><span>{role.userCount} usuários</span><strong>{role.permissions.length} permissões</strong></footer></article>)}</section><section className="panel permission-matrix-panel"><div className="panel-header"><h2>Matriz de permissões</h2><span className="permission-caption">✓ permitido · — não concedido</span></div><div className="permission-matrix-scroll"><table className="permission-matrix"><thead><tr><th>Permissão</th>{adminRoles.map((role) => <th key={role.id}>{role.name}</th>)}</tr></thead><tbody>{permissionCatalog.map((group) => <Fragment key={group.group}><tr className="permission-group-row"><td colSpan={adminRoles.length + 1}>{group.group}</td></tr>{group.items.map((permission) => <tr key={permission.key}><td><strong>{permission.label}</strong><small>{permission.description}</small></td>{adminRoles.map((role) => <td key={`${role.id}-${permission.key}`}>{role.permissions.includes(permission.key) ? <span className="permission-yes" aria-label="Permitido"><Icon name="check" size={13}/></span> : <span className="permission-no" aria-label="Não concedido">—</span>}</td>)}</tr>)}</Fragment>)}</tbody></table></div></section><div className="governance-context-note"><span className="governance-context-icon">02</span><div><strong>Ocultar botão não substitui autorização.</strong><p>A interface pode adaptar a experiência ao perfil, mas a API deverá validar cada permissão novamente antes de qualquer leitura ou alteração protegida.</p></div></div><p className="demo-note">A matriz representa a configuração-base planejada para o RBAC.</p></div>;
}
