import type { Permission } from "./types";

export const demoPermissions = new Set<Permission>([
  "dashboard.read",
  "orders.read",
  "orders.write",
  "preorders.read",
  "preorders.write",
  "payments.read",
  "payments.write",
  "products.read",
  "products.write",
  "kits.read",
  "kits.write",
  "categories.read",
  "categories.write",
  "inventory.read",
  "inventory.write",
  "inventory.adjust",
  "inventory.lots.write",
  "customers.read",
  "customers.write",
  "b2b.read",
  "b2b.write",
  "b2b.orders.write",
  "b2b.pricing.read",
  "b2b.pricing.write",
  "marketing.read",
  "marketing.write",
  "content.read",
  "content.write",
  "finance.read",
  "finance.write",
  "reports.read",
  "reports.export",
  "team.read",
  "team.write",
  "roles.read",
  "roles.manage",
  "sessions.read",
  "sessions.revoke",
  "audit.read",
  "settings.read",
  "settings.write",
  "security.read",
  "security.write",
]);

export function can(permission: Permission) {
  return demoPermissions.has(permission);
}
