import { Icon } from "../../../components/icon";
import { PageHeader } from "../../../components/page-header";
import { StatCard } from "../../../components/stat-card";
import { Button } from "../../../components/ui";
import { securityPolicies, securityPosture } from "../../../data/mock-admin";

export default function SecuritySettingsPage() {
  const required = securityPosture.filter((item) => item.status === "required").length;
  const backend = securityPosture.filter((item) => item.status === "backend").length;
  return <div className="page-stack security-settings-page"><PageHeader eyebrow="Configurações / Segurança" title="Segurança administrativa" description="Políticas que protegerão autenticação, sessão, ações sensíveis e dados da operação." actions={<Button icon="check" disabled title="Persistência de políticas será habilitada com backend">Salvar alterações</Button>}/><section className="stats-grid governance-stats"><StatCard label="Políticas" value={String(securityPolicies.length)} detail="parâmetros definidos" icon="shield" tone="green"/><StatCard label="Obrigatórios" value={String(required)} detail="controles de arquitetura" icon="lock" tone="green"/><StatCard label="Aguardando backend" value={String(backend)} detail="não simulados no navegador" icon="clock" tone="orange"/><StatCard label="Segredos no client" value="0" detail="regra obrigatória" icon="key" tone="neutral"/></section><section className="security-policy-grid">{securityPolicies.map((policy) => <article className="panel security-policy-card" key={policy.id}><header><span className={`security-policy-icon security-policy-${policy.tone}`}><Icon name={policy.icon} size={16}/></span><div><h2>{policy.title}</h2><p>{policy.description}</p></div></header><div className="security-policy-value"><span>{policy.label}</span><strong>{policy.value}</strong></div><label className="security-policy-control"><input type="checkbox" checked={policy.enabled} readOnly disabled/><span>{policy.enabled ? "Habilitado na política-base" : "Desabilitado na política-base"}</span></label></article>)}</section><section className="panel security-posture-panel"><div className="panel-header"><h2>Postura exigida para produção</h2><span className="permission-caption">estado arquitetural</span></div><div className="security-posture-list">{securityPosture.map((item) => <div key={item.id}><span className={`posture-status posture-${item.status}`}><Icon name={item.status === "required" ? "check" : "clock"} size={13}/></span><div><strong>{item.title}</strong><p>{item.description}</p></div><em>{item.status === "required" ? "Obrigatório" : "Backend"}</em></div>)}</div></section><div className="security-warning-panel"><Icon name="alert" size={17}/><div><strong>Nenhuma política desta tela é aplicada apenas pelo frontend.</strong><p>Cookies seguros, MFA, rate limiting, CSRF, hashing, revogação e autorização precisam existir na camada de servidor. Os controles permanecem bloqueados até essa integração.</p></div></div><p className="demo-note">Configurações exibidas são a política-base planejada, ainda sem persistência.</p></div>;
}
